name: Release Workflow
on:
  release:
    types: [published]

jobs:
  release:
    env:
      REF: ${{ github.ref }}
    name: Release Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          docker build \
            -t ghcr.io/leakytap/aws-cli-kube:${REF##*/} \
            -t ghcr.io/leakytap/aws-cli-kube:latest .

      - name: Push
        run: |
          docker login ghcr.io -u leakytap -p ${{ secrets.PAT }}
          docker push ghcr.io/leakytap/aws-cli-kube:${REF##*/}
          docker push ghcr.io/leakytap/aws-cli-kube:latest
